force-app/main/default/objects/Case_History__c/Case_History__c.object-meta.xml
<CustomObject>
    <description>Objeto filho do Case_Request__c. Este objeto serve para armazenar os históricos de cada Case Request. Separa as responsabilidades e facilita na compreensão</description>
    <label>Case History</label>
    <nameField>
        <label>Case_History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_History__c/fields/Case_Request__c.field-meta.xml
<CustomField>
    <fullName>Case_Request__c</fullName>
    <description>Campo de relacionamento master detail com o objeto case request.</description>
    <label>Case_Request</label>
    <referenceTo>Case_Request__c</referenceTo>
    <relationshipLabel>Case Histories</relationshipLabel>
    <relationshipName>Case_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_History__c/fields/SLA_Met__c.field-meta.xml
<CustomField>
    <fullName>SLA_Met__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Armazena um valor true ou false para caso o case request tenha cumprido o SLA Deadline ou não</description>
    <label>SLA Met</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/Case_Request__c.object-meta.xml
<CustomObject>
    <description>Case Request é um objeto customizado utilizado para registrar pedido ao setor de suporte. Neste objeto podemos gerenciar os pedidos de forma mais organizada, possuindo campos personalizados específicos para este fim.</description>
    <label>Case Request</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Case Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Request__c/fields/Resolution_Notes__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Notes__c</fullName>
    <description>Campo para registrar as informações de resolução e observações feitas pela equipe de suporte.</description>
    <label>Resolution Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/SLA_Deadline__c.field-meta.xml
<CustomField>
    <fullName>SLA_Deadline__c</fullName>
    <description>Data e hora limite para cumprimento do SLA definido para o caso.</description>
    <label>SLA Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Este é o campo referente ao Status da solicitação, ele indica em que status a solicitação está no momento.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseRequestHandlerTest.cls
/**
* @File Name : CaseRequestHandlerTest.cls
* @Description : Class responsible for testing the class CaseRequestHandler
* @Author : Anderson Carvalho da Silva
* @Last Modified By : Anderson Carvalho da Silva
* @Last Modified On : May 21, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | May 21, 2025 | Anderson Carvalho da Silva | Initial Version
**/

@IsTest
public class CaseRequestHandlerTest {
    
    @testSetup 
    static void setupData() {
        Case_Request__c cr = new Case_Request__c(
            Status__c = 'New'
        );
        insert cr;
    }
    
    @isTest 
    static void testCreatesHistoryWhenClosed() {
        Case_Request__c crToUpdate = [SELECT Id, Status__c, Resolution_Notes__c FROM Case_Request__c WHERE Status__c = 'New' LIMIT 1];
        
        crToUpdate.Status__c = 'Closed';
        crToUpdate.Resolution_Notes__c = 'Test Resolution Notes';
        update crToUpdate;

        List<Case_History__c> results = [
            SELECT Id FROM Case_History__c WHERE Case_Request__c = :crToUpdate.Id
        ];

        System.assertEquals(1, results.size(), 'Deveria retornar 1 registro');
    }

    @isTest 
    static void testCreatesHistoryWhenClosedWithoutResolutionNotes() {
        Case_Request__c crToUpdate = [SELECT Id, Status__c, Resolution_Notes__c FROM Case_Request__c WHERE Status__c = 'New' LIMIT 1];        
        crToUpdate.Status__c = 'Closed';
        
        Test.startTest();
            try {
                update crToUpdate;
                System.assert(false, 'Esperava falha por campo obrigatório ausente');
            } catch (DmlException e) {
                System.assert(e.getMessage().contains('Resolution Notes'), 'Mensagem de erro não corresponde');
            }
        Test.stopTest();
    }

    @isTest 
    static void testCreatesHistoryWhenSlaNotMet() {
        Case_Request__c crToUpdate = [SELECT Id, Status__c, Resolution_Notes__c, SLA_Deadline__c  FROM Case_Request__c WHERE Status__c = 'New' LIMIT 1];
        crToUpdate.SLA_Deadline__c = Datetime.now().addDays(-1);
        crToUpdate.Status__c = 'Closed';
        crToUpdate.Resolution_Notes__c = 'Test Resolution Notes';
        update crToUpdate;

        List<Case_History__c> results = [
            SELECT Id, SLA_Met__c FROM Case_History__c WHERE Case_Request__c = :crToUpdate.Id ORDER BY CreatedDate DESC
        ];

        System.assertEquals(false, results[0].SLA_Met__c , 'SLA foi cumprido.');
    }
}