force-app/main/default/objects/Case_History__c/Case_History__c.object-meta.xml
<CustomObject>
    <description>Objeto filho do Case_Request__c. Este objeto serve para armazenar os históricos de cada Case Request. Separa as responsabilidades e facilita na compreensão</description>
    <label>Case History</label>
    <nameField>
        <label>Case_History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_History__c/fields/Case_Request__c.field-meta.xml
<CustomField>
    <fullName>Case_Request__c</fullName>
    <description>Campo de relacionamento master detail com o objeto case request.</description>
    <label>Case_Request</label>
    <referenceTo>Case_Request__c</referenceTo>
    <relationshipLabel>Case Histories</relationshipLabel>
    <relationshipName>Case_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_History__c/fields/SLA_Met__c.field-meta.xml
<CustomField>
    <fullName>SLA_Met__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Armazena um valor true ou false para caso o case request tenha cumprido o SLA Deadline ou não</description>
    <label>SLA Met</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/Case_Request__c.object-meta.xml
<CustomObject>
    <description>Case Request é um objeto customizado utilizado para registrar pedido ao setor de suporte. Neste objeto podemos gerenciar os pedidos de forma mais organizada, possuindo campos personalizados específicos para este fim.</description>
    <label>Case Request</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Case Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Este é o campo referente ao Status da solicitação, ele indica em que status a solicitação está no momento.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseRequestRestResource.cls
/**
* @File Name : CaseRequestRestResource.cls
* @Description : Class responsible for exposing a RestResource that, given a caseId, returns JSON
* @Author : Anderson Carvalho da Silva
* @Last Modified By : Anderson Carvalho da Silva
* @Last Modified On : May 21, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | May 21, 2025 | Anderson Carvalho da Silva | Initial Version
**/

@RestResource(urlMapping='/CaseRequest/*')
global with sharing class CaseRequestRestResource {

    @HttpGet
    global static void getCaseRequestInfo() {
        RestRequest request = RestContext.request;
        String caseId = request.requestURI.substring(request.requestURI.lastIndexOf('/') + 1);
        RestResponse response = RestContext.response;
        response.addHeader('Content-Type', 'application/json');

        Map<String, Object> responseMap = new Map<String, Object>();
        if (String.isBlank(caseId) || caseId.length() < 15) {
            response.statusCode = 400;
            response.responseBody = Blob.valueOf('{"error":"Invalid or missing CaseRequest Id"}');
            return;
        }
        
        try {
            Case_Request__c caseRequest = [
            SELECT Status__c, (SELECT SLA_Met__c FROM Case_Histories__r WHERE Case_Request__c = :caseId LIMIT 1) FROM Case_Request__c WHERE Id = :caseId LIMIT 1
            ];

            response.statusCode = 200;
            Boolean slaMet = !caseRequest.Case_Histories__r.isEmpty() ? caseRequest.Case_Histories__r[0].SLA_Met__c : null;
            responseMap.put('Status', caseRequest.Status__c);
            responseMap.put('Sla_Met', slaMet);

            response.responseBody = Blob.valueOf(JSON.serialize(responseMap));
        } catch (QueryException e) {
            response.statusCode = 404;
            response.responseBody = Blob.valueOf('{"error":"Case request not found"}');
        }
        
    }
}