force-app/main/default/objects/Case_History__c/Case_History__c.object-meta.xml
<CustomObject>
    <description>Objeto filho do Case_Request__c. Este objeto serve para armazenar os históricos de cada Case Request. Separa as responsabilidades e facilita na compreensão</description>
    <label>Case History</label>
    <nameField>
        <label>Case_History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_History__c/fields/Case_Request__c.field-meta.xml
<CustomField>
    <fullName>Case_Request__c</fullName>
    <description>Campo de relacionamento master detail com o objeto case request.</description>
    <label>Case_Request</label>
    <referenceTo>Case_Request__c</referenceTo>
    <relationshipLabel>Case Histories</relationshipLabel>
    <relationshipName>Case_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_History__c/fields/SLA_Met__c.field-meta.xml
<CustomField>
    <fullName>SLA_Met__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Armazena um valor true ou false para caso o case request tenha cumprido o SLA Deadline ou não</description>
    <label>SLA Met</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case_History__c/fields/Time_Closed__c.field-meta.xml
<CustomField>
    <fullName>Time_Closed__c</fullName>
    <description>Armazena o valor em que o objeto pai Case Request é fechado.</description>
    <label>Time Closed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/Case_Request__c.object-meta.xml
<CustomObject>
    <description>Case Request é um objeto customizado utilizado para registrar pedido ao setor de suporte. Neste objeto podemos gerenciar os pedidos de forma mais organizada, possuindo campos personalizados específicos para este fim.</description>
    <label>Case Request</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Case Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Request__c/fields/Resolution_Notes__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Notes__c</fullName>
    <description>Campo para registrar as informações de resolução e observações feitas pela equipe de suporte.</description>
    <label>Resolution Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/SLA_Deadline__c.field-meta.xml
<CustomField>
    <fullName>SLA_Deadline__c</fullName>
    <description>Data e hora limite para cumprimento do SLA definido para o caso.</description>
    <label>SLA Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Este é o campo referente ao Status da solicitação, ele indica em que status a solicitação está no momento.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseRequestRestResourceTest.cls
/**
* @File Name : CaseRequestRestResourceTest.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : May 23, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | May 23, 2025 |   | Initial Version
**/

@IsTest
public class CaseRequestRestResourceTest {

    @testSetup
    static void setupData() {
        Case_Request__c caseReq = new Case_Request__c(
            Status__c = 'Closed',
            SLA_Deadline__c = System.now().addDays(1),
            Resolution_Notes__c = 'Resolution Notes Example Test'
        );
        insert caseReq;

        Case_History__c history = new Case_History__c(
            Name = 'Case Request 000001 History',
            Case_Request__c = caseReq.Id,
            SLA_Met__c = true,
            Time_Closed__c = System.now()
        );
        insert history;
    }

    @isTest
    static void testGetCaseRequestInfoByIdSuccess() {
        Case_Request__c caseReq = [
            SELECT Id FROM Case_Request__c WHERE Status__c = 'Closed' LIMIT 1
        ];

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CaseRequest/' + caseReq.Id;
        req.httpMethod = 'GET';

        RestContext.request = req;
        RestContext.response = res;

        CaseRequestRestResource.getCaseRequestInfo();

        String responseBody = RestContext.response.responseBody.toString();
        Map<String, Object> resultMap = (Map<String, Object>) JSON.deserializeUntyped(responseBody);
        System.debug(resultMap);

        System.assertEquals('Closed', resultMap.get('Status'), 'Status deveria ser Closed');
        System.assertEquals(true, resultMap.get('Sla_Met'), 'SLA deveria ter sido cumprido');
    }

    @IsTest
    static void testGetCaseRequestInfoInvalidId() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CaseRequest/' + '04325';
        req.httpMethod = 'GET';

        RestContext.request = req;
        RestContext.response = res;

        CaseRequestRestResource.getCaseRequestInfo();

        String responseBody = RestContext.response.responseBody.toString();
        Map<String, Object> resultMap = (Map<String, Object>) JSON.deserializeUntyped(responseBody);
        System.debug(resultMap);

        System.assertEquals('Invalid or missing CaseRequest Id', resultMap.get('error'), 'Id deve ser válido');
        System.assertEquals(400, RestContext.response.statusCode, 'Status code deve ser 400');
    }

    @IsTest
    static void testGetCaseRequestInfoQueryException() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CaseRequest/' + 'a00gK504003w454QAQ';
        req.httpMethod = 'GET';

        RestContext.request = req;
        RestContext.response = res;

        CaseRequestRestResource.getCaseRequestInfo();

        String responseBody = RestContext.response.responseBody.toString();
        Map<String, Object> resultMap = (Map<String, Object>) JSON.deserializeUntyped(responseBody);
        System.debug(resultMap);

        System.assertEquals('Case request not found', resultMap.get('error'), 'Id deve ser existente');
        System.assertEquals(404, RestContext.response.statusCode, 'Status code deve ser 404');
    }
}