force-app/main/default/objects/Case_History__c/Case_History__c.object-meta.xml
<CustomObject>
    <description>Objeto filho do Case_Request__c. Este objeto serve para armazenar os históricos de cada Case Request. Separa as responsabilidades e facilita na compreensão</description>
    <label>Case History</label>
    <nameField>
        <label>Case_History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_History__c/fields/Case_Request__c.field-meta.xml
<CustomField>
    <fullName>Case_Request__c</fullName>
    <description>Campo de relacionamento master detail com o objeto case request.</description>
    <label>Case_Request</label>
    <referenceTo>Case_Request__c</referenceTo>
    <relationshipLabel>Case Histories</relationshipLabel>
    <relationshipName>Case_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_History__c/fields/SLA_Met__c.field-meta.xml
<CustomField>
    <fullName>SLA_Met__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Armazena um valor true ou false para caso o case request tenha cumprido o SLA Deadline ou não</description>
    <label>SLA Met</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case_History__c/fields/Time_Closed__c.field-meta.xml
<CustomField>
    <fullName>Time_Closed__c</fullName>
    <description>Armazena o valor em que o objeto pai Case Request é fechado.</description>
    <label>Time Closed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/Case_Request__c.object-meta.xml
<CustomObject>
    <description>Case Request é um objeto customizado utilizado para registrar pedido ao setor de suporte. Neste objeto podemos gerenciar os pedidos de forma mais organizada, possuindo campos personalizados específicos para este fim.</description>
    <label>Case Request</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Case Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Request__c/fields/SLA_Deadline__c.field-meta.xml
<CustomField>
    <fullName>SLA_Deadline__c</fullName>
    <description>Data e hora limite para cumprimento do SLA definido para o caso.</description>
    <label>SLA Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/CaseRequestService.cls
/**
* @File Name : CaseRequestService.cls
* @Description : Class responsible for executing the business rule
* @Author : Anderson Carvalho da Silva
* @Last Modified By : Anderson Carvalho da Silva
* @Last Modified On : May 21, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | May 21, 2025 | Anderson Carvalho da Silva | Initial Version
**/

public class CaseRequestService {
	public static Case_History__c buildHistory(Case_Request__c caseRequest, Datetime now) {
        Boolean isSLADeadlineMet = caseRequest.SLA_Deadline__c != null && now <= caseRequest.SLA_Deadline__c;

        return new Case_History__c(
            Name = 'Case Request ' + caseRequest.Name + ' History',
            Case_Request__c = caseRequest.Id,
            Time_Closed__c = now,
            SLA_Met__c = isSLADeadlineMet
        );
    }
}