force-app/main/default/objects/Case_Request__c/Case_Request__c.object-meta.xml
<CustomObject>
    <description>Case Request é um objeto customizado utilizado para registrar pedido ao setor de suporte. Neste objeto podemos gerenciar os pedidos de forma mais organizada, possuindo campos personalizados específicos para este fim.</description>
    <label>Case Request</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Case Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Request__c/fields/Resolution_Notes__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Notes__c</fullName>
    <description>Campo para registrar as informações de resolução e observações feitas pela equipe de suporte.</description>
    <label>Resolution Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/SLA_Deadline__c.field-meta.xml
<CustomField>
    <fullName>SLA_Deadline__c</fullName>
    <description>Data e hora limite para cumprimento do SLA definido para o caso.</description>
    <label>SLA Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Este é o campo referente ao Status da solicitação, ele indica em que status a solicitação está no momento.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Request__c/recordTypes/Support_Premium.recordType-meta.xml
<RecordType>
    <fullName>Support_Premium</fullName>
    <active>true</active>
    <description>Record type para usuários com permissão de Support Premium</description>
    <label>Support Premium</label>
</RecordType>

force-app/main/default/classes/CaseRequestDetailService.cls
/**
* @File Name : CaseRequestDetailService.cls
* @Description : Class responsible for implementing the business logic of the requests made by the controller.
* @Author : Anderson Carvalho da Silva
* @Last Modified By : Anderson Carvalho da Silva
* @Last Modified On : May 21, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | May 21, 2025 | Anderson Carvalho da Silva | Initial Version
**/

public with sharing class CaseRequestDetailService {

    public static Map<String, Object> getSLAInfo(Id caseRequestId) {
        Case_Request__c req = [
            SELECT SLA_Deadline__c, Status__c, CreatedDate, Resolution_Notes__c 
            FROM Case_Request__c 
            WHERE Id = :caseRequestId 
            LIMIT 1
        ];

        Long millisRemaining = req.Status__c != 'Closed' ? req.SLA_Deadline__c.getTime() - DateTime.now().getTime() : 0;

        Long totalMilliseconds = req.SLA_Deadline__c.getTime() - req.CreatedDate.getTime();

        Boolean supportPremiumUser = supportPremiumUser('Support_Premium');

        return new Map<String, Object>{
            'slaEnd' => req.SLA_Deadline__c,
            'totalMilliseconds' => totalMilliseconds,
            'millisRemaining' => millisRemaining,
            'status' => req.Status__c,
            'resolutionNotes' => req.Resolution_Notes__c,
            'supportPremiumUser' => supportPremiumUser
        };
    }

    public static Map<String, Object> reopenCaseRequest(Id caseRequestId) {
        List<Case_Request__c> caseRequests = [
            SELECT Status__c 
            FROM Case_Request__c 
            WHERE Id = :caseRequestId 
            LIMIT 1
        ];
        Boolean isSupportPremiumUser = SupportPremiumUser('Support_Premium');

        if(!caseRequests.isEmpty()) {
            Case_Request__c caseRequest = caseRequests[0];
                if(isSupportPremiumUser) {
                caseRequest.Status__c = 'In Progress';
                Database.update(caseRequest);
                return new Map<String, Object>{
                    'message' => 'Caso reaberto com sucesso!'
                };
            } else {
                return new Map<String, Object>{
                    'error' => 'Você não tem permissão suficiente parar reabrir Casos.'
                };
            }
        }
        return new Map<String, Object>{
            'error' => 'Caso não encontrado'
        };
    }

    private static Boolean supportPremiumUser(String permissionSetName) {
        Id currentUserId = UserInfo.getUserId();

        List<PermissionSetAssignment> psa = [
            SELECT Id 
            FROM PermissionSetAssignment 
            WHERE AssigneeId = :currentUserId 
            AND PermissionSet.Name = :permissionSetName
        ];

        return !psa.isEmpty();
    }
}