force-app/main/default/objects/Case_Request__c/Case_Request__c.object-meta.xml
<CustomObject>
    <description>Case Request é um objeto customizado utilizado para registrar pedido ao setor de suporte. Neste objeto podemos gerenciar os pedidos de forma mais organizada, possuindo campos personalizados específicos para este fim.</description>
    <label>Case Request</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Case Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Request__c/fields/Resolution_Notes__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Notes__c</fullName>
    <description>Campo para registrar as informações de resolução e observações feitas pela equipe de suporte.</description>
    <label>Resolution Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/SLA_Deadline__c.field-meta.xml
<CustomField>
    <fullName>SLA_Deadline__c</fullName>
    <description>Data e hora limite para cumprimento do SLA definido para o caso.</description>
    <label>SLA Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Este é o campo referente ao Status da solicitação, ele indica em que status a solicitação está no momento.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Request__c/recordTypes/Support_Premium.recordType-meta.xml
<RecordType>
    <fullName>Support_Premium</fullName>
    <active>true</active>
    <description>Record type para usuários com permissão de Support Premium</description>
    <label>Support Premium</label>
</RecordType>

force-app/main/default/classes/CaseRequestDetailTest.cls
@IsTest
public class CaseRequestDetailTest {

    @TestSetup
    static void setupData(){
        Case_Request__c caseRequest = new Case_Request__c(
            Status__c = 'New',
            SLA_Deadline__c = System.now()+1
        );
        insert caseRequest;
    }

    @IsTest
    static void testGetSLAInfo() {
        Case_Request__c caseRequestQuery = [SELECT Id, Status__c, SLA_Deadline__c FROM Case_Request__c WHERE Status__c = 'New' LIMIT 1];

        Map<String, Object> caseInfo = (Map<String, Object>) CaseRequestDetailController.getSLAInfo(caseRequestQuery.Id);

        System.assertEquals(caseRequestQuery.SLA_Deadline__c, caseInfo.get('slaEnd'));
        System.assertEquals(caseRequestQuery.Status__c, caseInfo.get('status'));

    }
    
    static User createUser(Boolean hasPermission) {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User u = new User(
            Alias = 'tuser',
            Email = 'test' + Math.random() + '@example.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'User',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'testuser' + Math.random() + '@example.com'
        );
        insert u;

        Group queue = [SELECT Id FROM Group where type = 'Queue' and Name = 'Support Premium Queue' limit 1];

        GroupMember gm = new GroupMember(
            GroupId = queue.Id,
            UserOrGroupId = u.Id
        );
        insert gm;

        if (hasPermission) {
            PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Support_Premium' LIMIT 1];
            insert new PermissionSetAssignment(AssigneeId = u.Id, PermissionSetId = ps.Id);
        }
        return u;
    }

    @isTest
    static void testReopenWithPermission() {
        User u = createUser(true);
        System.runAs(u) {
            Case_Request__c cr = new Case_Request__c(Status__c = 'Closed', Resolution_Notes__c = 'Test example');
            insert cr;

            System.debug([SELECT RecordType.Name, Owner.Name FROM Case_Request__c]);
            Map<String, Object> res = CaseRequestDetailController.reopenCaseRequest(cr.Id);
            cr = [SELECT Status__c FROM Case_Request__c WHERE Id = :cr.Id];
            
            System.assertEquals('In Progress', cr.Status__c);
            System.assertEquals('Caso reaberto com sucesso!', res.get('message'));
        }
    }

    @isTest
    static void testReopenWithoutPermission() {
        User u = createUser(false);
        System.runAs(u) {
            Case_Request__c cr = new Case_Request__c(Status__c = 'Closed', Resolution_Notes__c = 'Test example');
            insert cr;

            Map<String, Object> res = CaseRequestDetailController.reopenCaseRequest(cr.Id);
            cr = [SELECT Status__c FROM Case_Request__c WHERE Id = :cr.Id];

            System.assertEquals('Closed', cr.Status__c);
            System.assertEquals('Você não tem permissão suficiente parar reabrir Casos.', res.get('error'));
        }
    }
    @isTest
    static void testReopenCaseRequest_CaseNotFound() {
        Id fakeId = Id.valueOf('a01000000000000AAA');

        Test.startTest();
        Map<String, Object> result = CaseRequestDetailController.reopenCaseRequest(fakeId);
        Test.stopTest();

        System.assertEquals(true, result.containsKey('error'), 'Deveria conter a chave "error"');
        System.assertEquals('Caso não encontrado', result.get('error'), 'Mensagem de erro incorreta');
    }
}